version: "3.9"
services:
  flaskapp:
    image: flaskapp
    build:
      context: .
      dockerfile: Backend_Dockerfile
    ports:
      - 5000:5000
    networks:
      - backend

networks:
  backend:
    driver: bridge