version: "3.9"
services:
  backend:
    build: ../FlaskApp/.
    image: manjunath777rgowda/chatbot-backend
    container_name: chatbot-backend
    ports:
      - 5000:5000
    # networks:
    #   - chatbot-network
      
  frontend:
    build: ../Chatbot/.
    image: manjunath777rgowda/chatbot-frontend
    container_name: chatbot-frontend
    ports:
      - 5173:5173
    # networks:
    #   - chatbot-network
    
  nginx:
    image: nginx:latest
    container_name: nginx-chatbot
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www
    ports:
      - 80:80
    # networks:
    #   - chatbot-network

# networks:
#   chatbot-network:
#     driver: bridge